---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine
    tag: "3.6"

inputs: 
- name: source-code

run:
  path: sh
  dir: source-code
  args:
  - -ec
  - |
    sleep 60