---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"

inputs: 
- name: combining-gate
- name: build-number

run:
  path: sh
  dir: combining-gate
  args:
  - -ec
  - |
    build number cat $(../build-number/version) has fully passed
    
    echo "passed:"
    cat passed
    
    echo ""
    
    echo "metadata:"
    cat metadata