---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"

inputs:
- name: build-number

outputs: 
- name: gen

run:
  path: sh
  dir: gen
  args:
  - -exc
  - |
    BUILD_NUMBER=$(cat ../build-number/version)
    # create a new autoclose gate based build number and 2 known build forks (map and common)
    gatefile="$BUILD_NUMBER.autoclose"

    echo "package-map/$BUILD_NUMBER" >> "$gatefile"
    echo "package-common/$BUILD_NUMBER" >> "$gatefile"