---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"

inputs:
- name: build-number
outputs: 
- name: gen

run:
  path: sh
  dir: gen
  args:
  - -exc
  - |
    x=$(cat ../build-number/version)
    echo $x > $x