resource_types:
- name: gate-resource
  type: docker-image
  source:
    repository: meshcloud/gate-resource
- name: semver_c
  type: registry-image
  source:
    repository: concourse/semver-resource

gate-source: &gate-source
  git: 
    uri: git@github.com:arcticShadow/gate-resource-example.git
    private_key: ((gh_token))
    branch: gates

resources:
  - name: repo
    type: git
    source:
      uri: git@github.com:arcticShadow/gate-resource-example.git
      private_key: ((gh_token))
      branch: master

  - name: package-map-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: package-map

  - name: package-common-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: package-common

  - name: combining-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: combining-gate

  - name: build-number
    type: semver_c
    source:
      driver: s3
      initial_version: 0.0.1
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      session_token: ((aws-session-token))
      bucket: stl-concourse-resources
      region_name: us-west-2
      key: gate-example/build-number2

jobs:
  - name: Start
    plan:
      - put: build-number
        params:
          bump: major

  - name: setup combining gate
    plan:
      - get: build-number
        trigger: true
        passed:
          - Start
      - get: repo
      - task: create autoclose gate file
        file: repo/ci/tasks/gen-autoclose.yml
      - put: put autoclose gate file
        resource: combining-gate
        params:
          item_file: gen/*

  - name: build map
    plan:
      - get: build-number
        trigger: true
        passed: 
          - setup combining gate
      - get: repo
      - task: build
        file: repo/ci/tasks/build-map.yml
        input_mapping:
          source-code: repo
      - task: pass gate file
        file: repo/ci/tasks/gen-simple.yml
      - put: put pass gate file
        resource: package-map-gate
        params:
          item_file: gen/*

  - name: build common
    plan:
      - get: build-number
        trigger: true
        passed: 
          - setup combining gate
      - get: repo
      - task: build
        file: repo/ci/tasks/build-common.yml
        input_mapping:
          source-code: repo
      - task: pass gate file
        file: repo/ci/tasks/gen-simple.yml
      - put: put pass gate file
        resource: package-common-gate
        params:
          item_file: gen/*
    
  - name: combine gates
    plan:
      - in_parallel:
        - get: build-number
          passed:
            - setup combining gate
        - get: package-map-gate
          trigger: true
        - get: package-common-gate
          trigger: true
      - put: combining-gate
        params:
          update_autoclose: true
  - name: echo
    plan:
      - in_parallel:
        - get: repo
        - get: build-number
          passed:
            - combine gates
        - get: combining-gate
          trigger: true
          version: every
      - task: echo
        file: repo/ci/tasks/echo.yml

  # - name: push-autogate
  #   plan:
  #   - get: repo
  #   - in_parallel:
  #     - get: a-gate
  #     - get: b-gate
  #   - task: gen
  #     file: repo/ci/tasks/gen-autoclose.yml
  #   - put: auto-gate
  #     params:
  #       item_file: gen/*

  # - name: autoclose-autogate
  #   plan:
  #     - in_parallel:
  #       - get: a-gate
  #         trigger: true
  #       - get: b-gate
  #         trigger: true
  #     - put: auto-gate
  #       params:
  #         update_autoclose: true

  # - name: echo
  #   plan:
  #     - in_parallel:
  #       - get: repo
  #       - get: auto-gate
  #         trigger: true
  #         version: every
  #     - task: echo
  #       file: repo/ci/tasks/echo.yml