resource_types:
- name: gate-resource
  type: docker-image
  source:
    repository: meshcloud/gate-resource

gate-source: &gate-source
  git: 
    uri: git@github.com:arcticShadow/gate-resource-example.git
    private_key: b8b955d2fb2513f44810f1cbff8d30dd24f3b30d
    branch: gates

resources:
  - name: repo
    type: git
    source:
      uri: git@github.com:arcticShadow/gate-resource-example.git
      private_key: b8b955d2fb2513f44810f1cbff8d30dd24f3b30d
      branch: master

  - name: a-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: a

  - name: b-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: b

  - name: auto-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: autogate

jobs:
  - name: push-a
    plan:
    - get: repo
    - task: gen
      file: repo/ci/tasks/gen-simple.yml
    - put: a-gate
      params:
        item_file: gen/*
  
  - name: push-b
    plan:
    - get: repo
    - task: gen
      file: repo/ci/tasks/gen-simple.yml
    - put: b-gate
      params:
        item_file: gen/*
    
  - name: push-autogate
    plan:
    - get: repo
    - aggregate:
      - get: a-gate
      - get: b-gate
    - task: gen
      file: repo/ci/tasks/gen-autoclose.yml
    - put: auto-gate
      params:
        item_file: gen/*

  - name: autoclose-autogate
    plan:
      - in_parallel:
        - get: a-gate
          trigger: true
        - get: b-gate
          trigger: true
      - put: auto-gate
        params:
          update_autoclose: true

  - name: echo
    plan:
      - in_parallel:
        - get: repo
        - get: auto-gate
          trigger: true
          version: every
      - task: echo
        file: repo/ci/tasks/echo.yml